#spring:
#  cloud:
#    nacos:
#      config:
#        server-addr: http://47.117.47.4:8848
#        namespace: 5870e3ac-34f3-4934-8a98-f4455d0527bb
#        group: home-auto-v3
spring:
  redis:
    database: 1
    ## 如果是单点的redis，打开以下配置 start
    host: 47.117.47.4
    port: 6379
    ## 单点redis配置结束 end
    password: landleaf@123.com
      ## 如果是sentinel，打开以下配置 start
    #sentinel:
    #master: smarthomeredis
    #nodes: [47.117.50.22:26379,47.117.48.27:26379,47.117.51.55:26379]
    ## sentinel配置结束
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    redisson:
      file: classpath:redisson.yml





